name: Quicksurvivalgames-Clan-Stats
version: ${project.version}
author: Simonsator
depends: [Clans]
main: de.simonsator.partyandfriends.clan.extensions.stats.quicksurvivalgames.QSGPlugin
description: Adds the stats of Quicksurvivalgames to clans